empresas_index:
  path:     '/'
  methods:  [GET]
  defaults: { _controller: WebManagementBundle:Empresa:index }

empresas_add:
  path:     '/add/'
  methods:  [GET]
  defaults: { _controller: WebManagementBundle:Empresa:add }

empresas_edit:
  path:     '/details/{id}'
  methods:  [GET]
  defaults: { _controller: WebManagementBundle:Empresa:details }

empresas_update:
  path:     '/details/{id}'
  methods:  [POST]
  defaults: { _controller: WebManagementBundle:Empresa:update }

empresas_delete:
  path:     '/details/{id}'
  methods:  [DELETE]
  defaults: { _controller: WebManagementBundle:Empresa:delete }

empresas_provincias_ajax:
  path:     '/provincia-ajax'
  methods:  [GET]
  defaults: { _controller: WebManagementBundle:Empresa:provinciaAjax }

empresas_pruebas:
  path:     '/pruebas'
  methods:  [GET]
  defaults: { _controller: WebManagementBundle:Empresa:pruebas }

