<?php

namespace WebManagementBundle\Repository;
use WebManagementBundle\Entity\Categoria;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Creamos una entidad vacia
     * @param $entity
     * @return int
     */
    public function add($entity, $idUsuario){
        $categoria = new Categoria();
        $categoria->setNombre("");
        $categoria->setFecha(new \DateTime);
        $categoria->setActivo(false);
        $categoria->setUsuario($idUsuario);

        $entity->persist($categoria);
        $entity->flush();

        return $categoria->getId();
    }
}
