<?php

namespace WebManagementBundle\Repository;

use WebManagementBundle\Entity\Empresa;
use WebManagementBundle\Entity\Provincias;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Metodo que crea una empresa vacia y retorna el id
     * @param $entityManager
     * @return int
     */
    public function add($entityManager, $categoria, $provincia, $municipio, $usuario){


        $empresa = new Empresa();
        $empresa->setNombre('');
        $empresa->setCategoria($categoria);
        $empresa->setProvincia($provincia);
        $empresa->setPoblacion($municipio);
        $empresa->setEmail('');
        $empresa->setActivo(false);
        $empresa->setPrioridad(1);
        $empresa->setFecha(new \DateTime);
        $empresa->setUsuario($usuario);

        $entityManager->persist($empresa);
        $entityManager->flush();

        return $empresa->getId();
    }
}
