<?php

namespace WebManagementBundle\Repository;

use WebManagementBundle\Entity\Municipios;

/**
 * MunicipiosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MunicipiosRepository extends \Doctrine\ORM\EntityRepository
{
    public function getMunicipiosProvincia($entity, $idProvincia){
        $qb = $entity->createQueryBuilder();
        $qb->select('n')
            ->from(Municipios::class,'n')
            ->where($qb->expr()->eq('n.idProvincia','?1'))
            ->setParameter('1', $idProvincia);

        return $qb->getQuery()->getResult();
    }
}
