<?php

namespace WebManagementBundle\Repository;

use WebManagementBundle\Entity\Provincias;

/**
 * ProvinciasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinciasRepository extends \Doctrine\ORM\EntityRepository
{

}
