<?php

namespace WebManagementBundle\Repository;
use WebManagementBundle\Entity\Tarea;

/**
 * TareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TareaRepository extends \Doctrine\ORM\EntityRepository
{
  public function newTask($entity, $nombreTarea, $usuario){
    $tarea = new Tarea();
    $tarea->setTarea($nombreTarea);
    $tarea->setFecha(new \DateTime);
    $tarea->setActivo(true);
    $tarea->setUsuario($usuario);

    $entity->persist($tarea);
    $entity->flush();
  }
}
